export default function AboutUs(){
    return(
        <div className="bg-[#f9fafb] h-[100vh] w-full" >
            <h1 className="p-5 font-bold text-5xl " >Hence<span className="font-bold text-5xl text-orange-500" >Prove</span></h1>
            <p className="p-5 pt-0" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde asperiores consectetur modi enim doloremque assumenda eaque ullam dolores soluta doloribus? Quia exercitationem voluptatem adipisci possimus, ea, iste laborum nihil beatae tempora labore recusandae quibusdam cupiditate iure, quaerat ratione totam. Nobis reprehenderit voluptates odit, ullam cum, at ab molestias voluptatibus beatae neque cumque atque eaque impedit.</p>
            <h1 className="p-5 font-bold text-5xl " >HenceProve<span className="font-bold text-5xl text-orange-500" >Robotics</span></h1>
            <p className="p-5 ">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic, distinctio provident! Maiores hic aut tenetur voluptas. Odit, vel harum qui cupiditate ea voluptatum optio exercitationem quis fuga. Placeat, neque dolore. Labore, commodi! Amet, libero optio quaerat reiciendis, culpa quas, aliquid quis laborum quae minima pariatur saepe in asperiores cumque blanditiis voluptatum ratione itaque quasi aliquam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint modi, obcaecati optio maxime voluptate nesciunt consectetur nulla numquam rem placeat nihil nam reprehenderit aperiam assumenda, quis, molestias inventore nisi vero labore commodi reiciendis. Voluptates maxime animi molestiae quas perspiciatis cum minus eligendi. Recusandae reprehenderit optio deserunt dignissimos quaerat. Assumenda fugit quas libero eum hic natus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius est obcaecati, doloremque possimus provident voluptates fugiat voluptatum rem! Quas eius officia dolorem, eligendi in ducimus deleniti esse, obcaecati optio possimus cupiditate mollitia doloribus iusto repudiandae sit debitis impedit? Aut eum ipsa itaque illum nobis impedit soluta nisi? Reprehenderit aut fuga veritatis, veniam recusandae rerum repudiandae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus, maxime eligendi impedit quae repellat, id necessitatibus veritatis quos praesentium quia, doloremque beatae tenetur? Fugiat, earum accusantium. Necessitatibus eum quis quaerat rem praesentium asperiores eaque. Esse aperiam omnis, maxime ut, eveniet odit quisquam minus ab, reprehenderit corrupti tenetur quidem distinctio repellendus ea sed magnam illo enim! Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, quod! Corporis placeat expedita iste unde neque voluptatum in, suscipit rerum, laudantium alias quae repudiandae cumque velit necessitatibus provident delectus nihil nobis dignissimos! Voluptate consequuntur, ipsam dicta qui deleniti neque. Ab earum iusto quidem, itaque unde minima. Cum dolorum reiciendis hic adipisci maxime ipsa accusamus ab.</p>
        </div>
    )

}